#!/bin/sh

# origin
go build ../
cp ../LICENSE ./
echo 'go build done'

# pacman
cp go-gsgm pacman/
cp LICENSE pacman/

cd pacman
makepkg -sfc pacman \
&& mv *.tar.zst ../
cd ..
echo 'pacman build done'
